### ISSUE TITLE
NoClassDefFoundError: jenkins/plugins/asynchttpclient/AHCUtils

### ISSUE THREAD

**Issue by Avec112** [camiloribeiro/cdeasy#13]
When I start jenkins this happens. 

```
jenkins_1  | Sep 29, 2016 11:25:13 AM com.cloudbees.jenkins.support.SupportPlugin writeBundle
jenkins_1  | WARNING: Could not attach 'update-center.md' to support bundle
jenkins_1  | java.lang.NoClassDefFoundError: jenkins/plugins/asynchttpclient/AHCUtils
jenkins_1  |    at com.cloudbees.jenkins.support.impl.UpdateCenter$1.writeTo(UpdateCenter.java:70)
jenkins_1  |    at com.cloudbees.jenkins.support.SupportPlugin.writeBundle(SupportPlugin.java:358)
jenkins_1  |    at com.cloudbees.jenkins.support.SupportPlugin.writeBundle(SupportPlugin.java:274)
jenkins_1  |    at com.cloudbees.jenkins.support.SupportPlugin$PeriodicWorkImpl$1.run(SupportPlugin.java:724)
jenkins_1  |    at java.lang.Thread.run(Thread.java:745)
jenkins_1  | Caused by: java.lang.ClassNotFoundException: jenkins.plugins.asynchttpclient.AHCUtils
jenkins_1  |    at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1373)
jenkins_1  |    at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1326)
jenkins_1  |    at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1079)
jenkins_1  |    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
jenkins_1  |    ... 5 more
```

**Comment by camiloribeiro** [comment]
Thanks for reporting. I have noticed it too. There is a fix waiting in line on jenkins official bug tracker:
https://issues.jenkins-ci.org/browse/JENKINS-38572

I will keep this open until the fix is released and we update, but there is no action from our side right not. Thanks. Camilo

**Comment by Avec112** [comment]
hehe...was just about to post it :-)

**Comment by camiloribeiro** [comment]
The pull request with the fix is taking forever, so I am fixing it by adding the missing dependency myself https://github.com/jenkinsci/support-core-plugin/pull/76
